version: '3'

services:
  web:
    build: .
    ports:
      - "8000:80" # Adjust port as needed
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root_secret

