controllers:
    resource: ../src/Controller/
    type: attribute
app_login:
    path: /login
    controller: App\Controller\ToDoController::login
    methods: [GET, POST]

app_health_check:
    path: /
    controller: App\Controller\ToDoController::healthCheck
    methods: [GET, POST]